F/T sensor fix and cable collisions
ipab-slmc/nextagea pull request #38
Opened 2021-05-06 14:05 UTC by VladimirIvan

- Adds collision spheres to account for dangling cables around the wrist.
- Fixes F/T sensor frames
- Adds F/T sensor gazebo tags
- Updates nextagea_moveit_config to account for new links in the collision matrix

2021-05-06 14:22 UTC, christian-rauch requested changes

2021-05-06 14:22 UTC, christian-rauch commented on nextagea_description/urdf/NextageA_robot.xacro
> +    </joint>
The indentation of the `joint` tag start/end is not aligned.

2021-05-06 14:22 UTC, christian-rauch commented on nextagea_moveit_config/.setup_assistant
> +    relative_path: urdf/NextageAOpen_gazebo_intel_realsense.urdf.xacro
Do we have a generic xacro without the sensor?

2021-05-06 14:22 UTC, christian-rauch commented on nextagea_description/urdf/NextageA_robot.xacro
> +    </link>
Not so important, but if we get more of these symmetric collision links we should make this a macro that is called with an 'L' or 'R' prefix, like here:
https://github.com/ipab-slmc/nextagea/blob/2e704c60146c4aba03fefaf1fb5920a70aaf296b/nextagea_description/urdf/NextageAOpen.urdf.xacro#L62-L67

2021-05-06 14:49 UTC, VladimirIvan commented on nextagea_moveit_config/.setup_assistant
> +    relative_path: urdf/NextageAOpen_gazebo_intel_realsense.urdf.xacro
We do but the way moveit works, you can generate the SRDF in setup assistant with the camera links, include them in the collision matrix, and if they are not present in the simpler model, moveit will just print a warning. If you use the simpler model to generate the SRDF instead and then load the one with the camera links, the camera link automatically collide and may cause problems.

2021-05-06 14:50 UTC, VladimirIvan commented on nextagea_description/urdf/NextageA_robot.xacro
> +    </link>
Definitely, I don't think we'll need more but if do, we can put them in a macro.

2021-05-06 15:04 UTC, christian-rauch approved these changes

2021-05-06 17:01 UTC, merged

2021-05-07 15:07 UTC, christian-rauch commented
Argh, should have tested this on the robot.

I am getting the error message:
```
[ERROR] [1620399925.906313841]: link 'LARM_JOINT4_Link_cables' is not unique.
[ERROR] [1620399925.973866310]: Unable to parse URDF
```
probably due to some copy&paste error @VladimirIvan .

2021-05-07 17:44 UTC, VladimirIvan commented
I moved the cable links from the urdf in `nextage_dynamic_pick_place` into here. Since that urdf extends this one it now has duplicate links. We have to remove these links from that repo and this error will go away.